### ISSUE TITLE
Test running application

### ISSUE THREAD

**Issue by chrira** [appuio/example-spring-boot-helloworld#69]
Add a test stage after the image build to check if the app starts inside the container.

```yaml
  test:
    needs: build-image
    runs-on: ubuntu-latest
    services:
      spring-boot-app:
        image: 'quay.io/appuio/example-spring-boot:pr-${{ github.event.pull_request.number }}'
    steps:
    - name: Run in container
      run: |
        echo start and wait
        sleep 20
        echo check app
        curl http://spring-boot-app:9000/health
```
